# Generated by Django 4.1.7 on 2023-04-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emcom', '0003_business_description_business_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emcom.business')),
            ],
        ),
    ]
